name: storykit
description: "A Flutter package for creating Instagram-like stories with customizable progress indicators, durations, and backgrounds."
version: 0.0.1
homepage: https://pub.dev/packages/storykit
repository: https://github.com/Raks-Javac/storykit
issue_tracker: https://github.com/Raks-Javac/storykit/issues

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

# Ignore files for publishing
publish_to: "https://pub.dev"
